name: shop_scan
description: A Flutter app to scan product labels and manage shopping lists.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  google_ml_kit: ^0.20.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
